### ISSUE TITLE
Streaming Data not ingesting to elasticsearch

### ISSUE THREAD

**Issue by manosec** [ercan5535/Structured-Streaming-Flask-Kafka-PySpark-Elasticsearch-Kibana-#1]
# This my error message:
pyspark.sql.utils.AnalysisException:  Failed to find data source: kafka. Please deploy the application as per the deployment section of "Structured Streaming + Kafka Integration Guide"

# config:
I'm using elasticsearch 7.17.1 and spark 3 using pyspark to ingest stream data.

jar file : elasticsearch-spark-30_2.12-7.17.1.jar

# code:

import time
import os

from pyspark.sql import SparkSession
from pyspark.sql.functions import *
from pyspark.sql.types import StructType, StringType, StructField

Define the Elasticsearch parameters
es_host = ES_SERVER
es_port = PORT

Define the schema for the Kafka message value
schema = StructType([
    StructField("labels", StructType([
        StructField("__name__", StringType()),
        StructField("instance", StringType()),
        StructField("job", StringType())
    ])),
    StructField("name", StringType()),
    StructField("value", StringType()),
    StructField("timestamp", StringType())
])

Create Spark Session
spark = SparkSession.builder.appName("StructuredStreaming").getOrCreate()
spark.sparkContext.setLogLevel('ERROR')

Read data from Kafka topic
df = spark \
  .readStream \
  .format("kafka") \
  .option("kafka.bootstrap.servers", SERVER) \
  .option("subscribe", TOPIC) \
  .option("startingOffsets", "earliest") \
  .load()

df.printSchema()

Convert Vale byte format to string format
df = df.selectExpr("CAST(value AS STRING)").select(from_json("value", schema).alias("data")).select("data.*")

Write to consol
query = \
    df_final \
    .writeStream \
    .format("console") \
    .outputMode("append") \
    .trigger(processingTime="5 seconds") \
    .start()

Write to elasticsearch
query = df_final.writeStream \
    .outputMode("append") \
    .format("org.elasticsearch.spark.sql") \
    .option("checkpointLocation", "tmp/") \
    .option("es.resource",index_name") \
    .option("es.nodes", es_host) \
    .option("es.port", es_port) \
    .start()

 query.awaitTermination()

# command:
sudo docker exec a2ad334434f6 spark-submit --master spark://a2ad334434f6:7077 --driver-class-path /opt/spark-apps/elasticsearch-spark-30_2.12-7.17.1.jar --total-executor-cores 1 --executor-cores 1 --executor-memory 1g --driver-memory 1g --name streaming_data /opt/spark-apps/testing.py

The text in the code are commented!

**Comment by ercan5535** [comment]
@manosec you look like you missed the `--packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.1` in your spark submit command. You need to add this to your spark submit command for using kafka with spark

**Comment by manosec** [comment]
Hi @ercan5535, i'll check and get back to you and thanks for responding to the issue right away.

**Comment by manosec** [comment]
Hi @ercan5535 still throwing an error

It is a kind of WARN message but the data is neither logged in the console nor stored in the DB. 

# Error
 
23/04/06 10:37:11 WARN ResolveWriteToStream: spark.sql.adaptive.enabled is not supported in streaming DataFrames/Datasets and will be disabled.

# command
spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.1 --jars elasticsearch-spark-30_2.12-8.5.3.jar spark.py

**Comment by manosec** [comment]
And onething i want to mention here is upon setting this.

spark = SparkSession.builder \
           .appName('Elastic') \
           .getOrCreate()
spark.sparkContext.setLogLevel("WARN")
spark.conf.set("spark.sql.adaptive.enabled","false")

The warning doesn't show up anymore but I'm not able to see the output in the console and the script closes right after the completion no output.

**Comment by ercan5535** [comment]
@manosec there is lots of WARN messages in spark therefore i set log level ERROR to see only outputs and errors.
and its a pipeline so you have to make sure every steps work well.
1- are you sure your kafka topic has data?
2- can u writeconsole after reading kafka topic which is after this:
df = spark
.readStream
.format("kafka")
.option("kafka.bootstrap.servers", SERVER)
.option("subscribe", TOPIC)
.option("startingOffsets", "earliest")
.load()

df.printSchema()

Convert Vale byte format to string format
df = df.selectExpr("CAST(value AS STRING)")

because if your schema transformation is not correct you will not see any data.
I spent too much time for schema operations :)

**Comment by manosec** [comment]
Hi @ercan5535, I have resolved this, while running from jupyter-notebook I'm able to see the output in the console. but have you got any error connecting to ES. I got this error, please let me know.

# Error

Py4JJavaError: An error occurred while calling o47.start.
: org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot detect ES version - typically this happens if the network/Elasticsearch cluster is not accessible or when targeting a WAN/Cloud instance without the proper setting 'es.nodes.wan.only'

Caused by: org.elasticsearch.hadoop.rest.EsHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[192.168.3.66:9200]] 


This IP is from my local network and I'm able to ingest data using a Python script that has Kafka consumer and elastic search client.

I know this is a simple network issue but if it is from a connection perspective I'm not able to connect with python right?

**Comment by manosec** [comment]
is there any modification need to add in elasticsearch.yml file, any config need change and I'm able to access the elasticsearch with postman from my local machine

**Comment by ercan5535** [comment]
@manosec `--jars elasticsearch-spark-30_2.12-8.5.3.jar` is for elasticsearch 8.5.3, you need to use for your elasticsearch version `--jars elasticsearch-spark-30_2.12-7.17.1.jar` or make sure versions are matched

**Comment by ercan5535** [comment]
and to connect a elasticsearch on local machine use localhost:9092

**Comment by manosec** [comment]
Okay @ercan5535 I'll try in my local machine, thanks for the suggestions.

**Comment by ercan5535** [comment]
Sure no problem. Im not an expert but love to help you. You can reach me on linkedin for anything ✌

**Comment by manosec** [comment]
Hi @ercan5535 I'm able to achieve it in a slightly different way, here is the code below:

# Define a batch function to write each batch of data to Elasticsearch

def insert_elasticsearch(batch_df, batch_id):
    try:
         es = Elasticsearch("http://192.168.1.1:9200")
         batch_dict = batch_df.toJSON().map(lambda x: json.loads(x)).collect()
         for doc in batch_dict:
             es.index(index="my_index", body=doc)
         print("Batch Data Ingested Successfully")
    except Exception as e:
        print(e)

query = df.writeStream \
    .foreachBatch(insert_elasticsearch \
    .outputMode("update")\
    .option("checkpointLocation", "/home/jovyan/elastic")\
    .start()
